### ISSUE TITLE
Environment details

### ISSUE THREAD

**Issue by sjdh** [hrhodin/NeuralSceneDecomposition#1]
Hi Helge,

Thanks for sharing your code. I am trying to get it running, but I keep getting errors due to package version issues.  I am not sure which package versions you used. Could you share which `pytorch` and `torchvision` versions you used? Or even better, can you generate a environment file with all package versions? 

Thanks a lot. 

Best regards,
Sjoerd

**Comment by hrhodin** [comment]
Perhaps its the python version? It needs python 3.

It was developed with pytorch 0.4, but we also run it with torch 1.2.0 and torchvision 0.4.0

Does this help?

**Comment by sjdh** [comment]
Thanks a lot.

Also with pytorch0.4 I get errors. After solving various package versioning problems, I ended up with this conda environment:

```
conda env create -n nsd
conda install -n nsd  -c pytorch python=3.6 pytorch==0.4 matplotlib numpy imageio torchvision=0.2.1-py36 pillow=6.2.1 h5py=2.10.0   tqdm=4.43.0-py_0
```
Unfortunately it still has errors. 
```
conda activate nsd
python test_detect_encode_decode.py
```
These are the errors:
```
Downloading: "https://download.pytorch.org/models/resnet50-19c8e357.pth" to /home/ubuntu/.torch/models/resnet50-19c8e357.pth
100%|█████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 102502400/102502400 [00:05<00:00, 17148046.79it/s]
Transferring weights...                                         
Warning, no match for layer4.0.conv1.weight, ignoring
Warning, no match for layer4.0.bn1.running_mean, ignoring           
Warning, no match for layer4.0.bn1.running_var, ignoring 
Warning, no match for layer4.0.bn1.weight, ignoring            
Warning, no match for layer4.0.bn1.bias, ignoring  
Warning, no match for layer4.0.conv2.weight, ignoring             
Warning, no match for layer4.0.bn2.running_mean, ignoring
Warning, no match for layer4.0.bn2.running_var, ignoring                                                              
Warning, no match for layer4.0.bn2.weight, ignoring     
Warning, no match for layer4.0.bn2.bias, ignoring                                                         
Warning, no match for layer4.0.conv3.weight, ignoring
Warning, no match for layer4.0.bn3.running_mean, ignoring                                                      
Warning, no match for layer4.0.bn3.running_var, ignoring                                                                                                                             
Warning, no match for layer4.0.bn3.weight, ignoring                                                                
Warning, no match for layer4.0.bn3.bias, ignoring                     
Warning, no match for layer4.0.downsample.0.weight, ignoring                                                          
Warning, no match for layer4.0.downsample.1.running_mean, ignoring
Warning, no match for layer4.0.downsample.1.running_var, ignoring                                                                    
Warning, no match for layer4.0.downsample.1.weight, ignoring
Warning, no match for layer4.0.downsample.1.bias, ignoring                                                                      
Warning, no match for layer4.1.conv1.weight, ignoring
Warning, no match for layer4.1.bn1.running_mean, ignoring                                                                   
Warning, no match for layer4.1.bn1.running_var, ignoring                                 
Warning, no match for layer4.1.bn1.weight, ignoring                                            
Warning, no match for layer4.1.bn1.bias, ignoring                                                             
Warning, no match for layer4.1.conv2.weight, ignoring      
Warning, no match for layer4.1.bn2.running_mean, ignoring
Warning, no match for layer4.1.bn2.running_var, ignoring          
Warning, no match for layer4.1.bn2.weight, ignoring
Warning, no match for layer4.1.bn2.bias, ignoring
Warning, no match for layer4.1.conv3.weight, ignoring
Warning, no match for layer4.1.bn3.running_mean, ignoring
Warning, no match for layer4.1.bn3.running_var, ignoring
Warning, no match for layer4.1.bn3.weight, ignoring
Warning, no match for layer4.1.bn3.bias, ignoring
Warning, no match for layer4.2.conv1.weight, ignoring
Warning, no match for layer4.2.bn1.running_mean, ignoring
Warning, no match for layer4.2.bn1.running_var, ignoring
Warning, no match for layer4.2.bn1.weight, ignoring
Warning, no match for layer4.2.bn1.bias, ignoring
Warning, no match for layer4.2.conv2.weight, ignoring
Warning, no match for layer4.2.bn2.running_mean, ignoring
Warning, no match for layer4.2.conv3.weight, ignoring
Warning, no match for layer4.2.bn3.running_mean, ignoring
Warning, no match for layer4.2.bn3.running_var, ignoring
Warning, no match for layer4.2.bn3.weight, ignoring
Warning, no match for layer4.2.bn3.bias, ignoring
Invalid param size(own=torch.Size([728, 128]) vs. source=torch.Size([1000, 2048])), skipping fc.weight
Invalid param size(own=torch.Size([728]) vs. source=torch.Size([1000])), skipping fc.bias
**Copied 215 elements, 52 skipped, and 58 target params without source**
Done image net weights...                          
Loading weights from config_dict['pretrained_network_path']
Transferring weights...                              
Copied 401 elements, 0 skipped, and 0 target params without source
Done loading weights from config_dict['pretrained_network_path']
Traceback (most recent call last):                 
  File "configs/test_detect_encode_decode.py", line 287, in <module>
    ignite.run(config_dict_module.__file__, config_dict)                                              
  File "configs/test_detect_encode_decode.py", line 100, in run                          
    predict()                                                       
  File "configs/test_detect_encode_decode.py", line 98, in predict
    output_dict_cuda = model(input_dict_cuda)              
  File "/home/ubuntu/anaconda3/envs/nsd/lib/python3.6/site-packages/torch/nn/modules/module.py", line 491, in __call__
    result = self.forward(*input, **kwargs)                       
  File "/home/ubuntu/NeuralSceneDecomposition/python/models/detect_encode_decode.py", line 250, in forward
    return self.forward_pose(input_dict)
  File "/home/ubuntu/NeuralSceneDecomposition/python/models/detect_encode_decode.py", line 859, in forward_pose
    input_dict_cropped, input_img_downscaled, ST_depth, affine_matrix_crop_multi, affine_matrix_uncrop_multi, affine_matrix_crop_raw, R_virt2orig = self.forward_detector(input_dict)
  File "/home/ubuntu/NeuralSceneDecomposition/python/models/detect_encode_decode.py", line 281, in forward_detector
    grid_downscale = F.affine_grid(affine_matrix_downscale, size=size)
  File "/home/ubuntu/anaconda3/envs/nsd/lib/python3.6/site-packages/torch/nn/functional.py", line 1879, in affine_grid
    return vision.affine_grid_generator(theta, size)
  File "/home/ubuntu/anaconda3/envs/nsd/lib/python3.6/site-packages/torch/nn/_functions/vision.py", line 24, in affine_grid_generator
    if not cudnn.is_acceptable(theta.data):
  File "/home/ubuntu/anaconda3/envs/nsd/lib/python3.6/site-packages/torch/backends/cudnn/__init__.py", line 87, in is_acceptable
    if _libcudnn() is None:             
  File "/home/ubuntu/anaconda3/envs/nsd/lib/python3.6/site-packages/torch/backends/cudnn/__init__.py", line 58, in _libcudnn
    'but linked against {}'.format(compile_version, __cudnn_version))                                                                                                                
RuntimeError: cuDNN version mismatch: PyTorch was compiled against 7102 but linked against 7605   
```

**Comment by sjdh** [comment]
Thanks for your help. I got `test_detect_encode_decode.py` working with the following environment:
```
conda create -n nsd -c pytorch python=3.6 pytorch==0.4 matplotlib numpy imageio torchvision=0.2.1 pillow=6.2.1 h5py=2.10.0   tqdm=4.43 cudnn=7.1.02 matplotlib=2.2.3 ipython scipy
```

The anaconda environment file looks like this
```
name: nsd
channels:
  - pytorch
  - defaults
dependencies:
  - _libgcc_mutex=0.1=main
  - backcall=0.1.0=py36_0
  - blas=1.0=openblas
  - ca-certificates=2020.1.1=0
  - certifi=2019.11.28=py36_1
  - cffi=1.14.0=py36h2e261b9_0
  - cudatoolkit=9.0=h13b8566_0
  - cudnn=7.1.2=cuda9.0_0
  - cycler=0.10.0=py36_0
  - dbus=1.13.12=h746ee38_0
  - decorator=4.4.2=py_0
  - expat=2.2.6=he6710b0_0
  - fontconfig=2.13.0=h9420a91_0
  - freetype=2.9.1=h8a8886c_1
  - glib=2.63.1=h5a9c865_0
  - gst-plugins-base=1.14.0=hbbd80ab_1
  - gstreamer=1.14.0=hb453b48_1
  - h5py=2.10.0=py36h7918eee_0
  - hdf5=1.10.4=hb1b8bf9_0
  - icu=58.2=h9c2bf20_1
  - imageio=2.8.0=py_0
  - intel-openmp=2019.4=243
  - ipython=7.13.0=py36h5ca1d4c_0
  - ipython_genutils=0.2.0=py36_0
  - jedi=0.16.0=py36_1
  - jpeg=9b=h024ee3a_2
  - kiwisolver=1.1.0=py36he6710b0_0
  - ld_impl_linux-64=2.33.1=h53a641e_7
  - libedit=3.1.20181209=hc058e9b_0
  - libffi=3.2.1=hd88cf55_4
  - libgcc-ng=9.1.0=hdf63c60_0
  - libgfortran-ng=7.3.0=hdf63c60_0
  - libopenblas=0.3.6=h5a2b251_2
  - libpng=1.6.37=hbc83047_0
  - libstdcxx-ng=9.1.0=hdf63c60_0
  - libtiff=4.1.0=h2733197_0
  - libuuid=1.0.3=h1bed415_2
  - libxcb=1.13=h1bed415_1
  - libxml2=2.9.9=hea5a465_1
  - matplotlib=2.2.3=py36hb69df0a_0
  - mkl=2018.0.3=1
  - nccl=1.3.5=cuda9.0_0
  - ncurses=6.2=he6710b0_0
  - ninja=1.9.0=py36hfd86e86_0
  - numpy=1.18.1=py36h94c655d_0
  - numpy-base=1.18.1=py36h2f8d375_1
  - olefile=0.46=py36_0
  - openssl=1.1.1e=h7b6447c_0
  - parso=0.6.2=py_0
  - pcre=8.43=he6710b0_0
  - pexpect=4.8.0=py36_0
  - pickleshare=0.7.5=py36_0
  - pillow=6.2.1=py36h34e0f95_0
  - pip=20.0.2=py36_1
  - prompt-toolkit=3.0.4=py_0
  - prompt_toolkit=3.0.4=0
  - ptyprocess=0.6.0=py36_0
  - pycparser=2.20=py_0
  - pygments=2.6.1=py_0
  - pyparsing=2.4.6=py_0
  - pyqt=5.9.2=py36h05f1152_2
  - python=3.6.10=hcf32534_1
  - python-dateutil=2.8.1=py_0
  - pytorch=0.4.0=py36hdf912b8_0
  - pytz=2019.3=py_0
  - qt=5.9.7=h5867ecd_1
  - readline=8.0=h7b6447c_0
  - scipy=1.4.1=py36habc2bb6_0
  - setuptools=46.1.1=py36_0
  - sip=4.19.8=py36hf484d3e_0
  - six=1.14.0=py36_0
  - sqlite=3.31.1=h7b6447c_0
  - tk=8.6.8=hbc83047_0
  - torchvision=0.2.1=py_2
  - tornado=6.0.4=py36h7b6447c_1
  - tqdm=4.43.0=py_0
  - traitlets=4.3.3=py36_0
  - wcwidth=0.1.8=py_0
  - wheel=0.34.2=py36_0
  - xz=5.2.4=h14c3975_4
  - zlib=1.2.11=h7b6447c_3
  - zstd=1.3.7=h0b5b093_0

```
